<?php
/*************************************************************************************/
/*                                                                                   */
/*      This file is not free software                                               */
/*                                                                                   */
/*      Copyright (c) Franck Allimant, CQFDev                                        */
/*      email : thelia@cqfdev.fr                                                     */
/*      web : http://www.cqfdev.fr                                                   */
/*                                                                                   */
/*************************************************************************************/

/**
 * Created by Franck Allimant, CQFDev <franck@cqfdev.fr>
 * Date: 27/10/2015 16:16
 */

namespace DynamicTemplates;

use Thelia\Core\Template\TheliaTemplateHelper;

class MyTemplateHelper extends TheliaTemplateHelper
{
    public function getActiveFrontTemplate()
    {
        return parent::getActiveFrontTemplate(); // TODO: Change the autogenerated stub
    }
}
